Repository GuillaumeDespaux/cyos, pull requests merged in 2024-02, with the labels that each got.

#1 Theme edit
  index.html
  main.js
  style.css
Labels: enhancement

#4 Visual improvement and issue correction
  index.html
  main.js
  style.css
Labels: bug, enhancement

#5 Scene images
  .DS_Store
  img/.DS_Store
  img/100.png
  img/14.jpeg
  img/16.webp
  img/3.webp
  img/6.jpeg
  main.js
Labels: improvement

#6 Visual improvement
  style.css
Labels: enhancement
